### ISSUE TITLE
Update pg

### ISSUE THREAD

**Issue by gideonthomas** [filerjs/filer-sql#2]
I think the fix for the problem that was causing [#473](https://github.com/mozilla/makedrive/issues/473) is in v4.0.0 of pg. So I believe that needs to be updated here.

cc @humphd

**Comment by alicoding** [comment]
That's a major update, so I think we should test this heavily before update this to 4.0.

**Comment by modeswitch** [comment]
Have you done a complete filer test run with this provider?
